export interface GlobalHotspot {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  flag: string;
  category: 'INTERNATIONAL_SANCTUARY' | 'TRANSIT_HUB' | 'DOMESTIC_SYNDICATE' | 'CROSS_BORDER_CORRIDOR';
  lat: number;
  lng: number;
  fugitiveCount: number;
  topOffenses: string[];
  extraditionStatus: string;
  interpolArticle: string;
  investigativeRationale: string;
  linkedFugitiveIds: string[];
  keyPersons: string[];
  treatyStatus: 'IN_FORCE' | 'MLAT_ONLY' | 'NO_TREATY_INTERPOL_ONLY';
}

export interface FlightArc {
  id: string;
  sourceId: string;
  sourceName: string;
  targetId: string;
  targetName: string;
  sourceCoords: [number, number]; // [lng, lat]
  targetCoords: [number, number]; // [lng, lat]
  corridorType: 'FINANCIAL_LAUNDERING' | 'LOGISTICS_SMUGGLING' | 'EXTRADITION_TRANSIT' | 'INSURGENCY_TRANSIT';
  description: string;
  density: 'HIGH' | 'CRITICAL' | 'MEDIUM';
}

export const GLOBAL_HOTSPOTS: GlobalHotspot[] = [
  // ── INTERNATIONAL SANCTUARY & TRANSIT HUBS ───────────────────
  {
    id: 'HOTSPOT-UAE',
    name: 'Dubai & Northern Emirates',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    category: 'INTERNATIONAL_SANCTUARY',
    lat: 25.2048,
    lng: 55.2708,
    fugitiveCount: 24,
    topOffenses: ['Financial Fraud', 'Money Laundering (PMLA)', 'Syndicate Direction', 'Organized Gold Smuggling'],
    extraditionStatus: 'Extradition Treaty Active (Signed 1999, Ratified 2000)',
    interpolArticle: 'Interpol Red Notice Art. 83 (Extradition Request Pending)',
    investigativeRationale: 'Primary offshore financial haven and corporate layer for hawala transfers and proxy company registrations linked to Western India syndicates.',
    linkedFugitiveIds: ['P-015', 'P-017', 'P-022', 'P-089', 'P-112', 'P-145'],
    keyPersons: ['Vikram Reddy (P-017)', 'Suresh Gupta (P-022)', 'Tahir Merchant Proxy'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-UK',
    name: 'London Metropolitan Area',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    category: 'INTERNATIONAL_SANCTUARY',
    lat: 51.5074,
    lng: -0.1278,
    fugitiveCount: 18,
    topOffenses: ['High-Value Bank Fraud (FEOA 2018)', 'Extradition Evasion', 'Corporate Embezzlement'],
    extraditionStatus: 'Extradition Treaty in Force (1992); Crown Prosecution Court Proceedings Active',
    interpolArticle: 'Interpol Red Notice Art. 83 & Fugitive Economic Offenders Act Notice',
    investigativeRationale: 'Favored legal battleground for absconding economic offenders seeking human-rights appeals to delay court-ordered extradition.',
    linkedFugitiveIds: ['P-020', 'P-028', 'P-095', 'P-133'],
    keyPersons: ['Rakesh Agarwal (P-020)', 'Tarun Sethi (P-028)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-CAN',
    name: 'Greater Toronto & Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    category: 'INTERNATIONAL_SANCTUARY',
    lat: 43.6532,
    lng: -79.3832,
    fugitiveCount: 14,
    topOffenses: ['Cross-Border Gang Logistics', 'Contract Killings', 'Arms Trafficking (Arms Act)', 'UAPA Offenses'],
    extraditionStatus: 'Bilateral Treaty 1987; Formal Extradition Package Transmitted via MEA',
    interpolArticle: 'Interpol Red Notice Art. 83 (High-Risk Kinetic Threat)',
    investigativeRationale: 'Logistical base for syndicated gang extortion, narcotics couriers, and remote recruitment targeting northern Indian states.',
    linkedFugitiveIds: ['P-035', 'P-038', 'P-074', 'P-180'],
    keyPersons: ['Deepak Joshi (P-038)', 'Sachin Gaikwad (P-035)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-USA',
    name: 'New York & West Coast Hub',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    category: 'INTERNATIONAL_SANCTUARY',
    lat: 40.7128,
    lng: -74.0060,
    fugitiveCount: 11,
    topOffenses: ['Transnational Cyber Fraud', 'VoIP Call Center Extortion', 'Identity Theft'],
    extraditionStatus: 'Extradition Treaty Signed 1997; Active FBI-CBI Law Enforcement Working Group',
    interpolArticle: 'Interpol Red Notice Art. 83 / DOJ Mutual Legal Assistance Request',
    investigativeRationale: 'Financial and cyber routing infrastructure for transatlantic wire fraud and money laundering schemes.',
    linkedFugitiveIds: ['P-021', 'P-025', 'P-118'],
    keyPersons: ['Praveen Malhotra (P-021)', 'Yogesh Bhatia (P-025)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-PAK',
    name: 'Karachi & Lahore Corridors',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    category: 'CROSS_BORDER_CORRIDOR',
    lat: 30.3753,
    lng: 69.3451,
    fugitiveCount: 22,
    topOffenses: ['Cross-Border Terrorism (UAPA)', 'FICN Counterfeit Currency', 'State Sanctuary', 'Organized Weapons Smuggling'],
    extraditionStatus: 'No Bilateral Extradition Treaty; Monitored via Interpol NCB New Delhi & FATF ICRG',
    interpolArticle: 'Interpol Red Notice Permanent Flag (UNSC 1267 Cross-Referenced)',
    investigativeRationale: 'Hostile sanctuary providing false identity documents, secure communication lines, and staging facilities for cross-border infiltrators.',
    linkedFugitiveIds: ['P-004', 'P-045', 'P-049', 'P-201'],
    keyPersons: ['Irfan Sheikh (P-045)', 'Sameer Khan (P-049)'],
    treatyStatus: 'NO_TREATY_INTERPOL_ONLY',
  },
  {
    id: 'HOTSPOT-NEP',
    name: 'Kathmandu Transit Basin',
    country: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    category: 'TRANSIT_HUB',
    lat: 28.3949,
    lng: 84.1240,
    fugitiveCount: 13,
    topOffenses: ['Porous Border Infiltration', 'Third-Country Transit Point', 'Smuggled Contraband', 'Fake Passports'],
    extraditionStatus: '1953 Extradition Treaty & SSB Coordination Protocol',
    interpolArticle: 'Interpol Red Notice Border Alert (SSB Land Checkpoints)',
    investigativeRationale: 'Open 1,751 km border utilized for covert entry/exit, identity swaps, and transit between Gulf hubs and northern India.',
    linkedFugitiveIds: ['P-046', 'P-048', 'P-162'],
    keyPersons: ['Vishal Dubey (P-046)', 'Anand Mishra (P-048)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-ROU',
    name: 'Bucharest Hub',
    country: 'Romania',
    countryCode: 'RO',
    flag: '🇷🇴',
    category: 'INTERNATIONAL_SANCTUARY',
    lat: 45.9432,
    lng: 24.9668,
    fugitiveCount: 7,
    topOffenses: ['ATM Skimming Synergies', 'Cybercrime Malware Distribution', 'Cryptocurrency Laundering'],
    extraditionStatus: 'Extradition Agreement under UN Convention Against Transnational Organized Crime (UNTOC)',
    interpolArticle: 'Interpol Red Notice Art. 83 / Europol Operational Liaison',
    investigativeRationale: 'Eastern European technical hub supplying ATM cloning hardware and cryptojacking infrastructure to Indian fraud operators.',
    linkedFugitiveIds: ['P-003', 'P-024', 'P-215'],
    keyPersons: ['Deepak Mehra (P-024)', 'European Carding Syndicate Proxy'],
    treatyStatus: 'MLAT_ONLY',
  },
  {
    id: 'HOTSPOT-BGD',
    name: 'Dhaka & Border Outposts',
    country: 'Bangladesh',
    countryCode: 'BD',
    flag: '🇧🇩',
    category: 'CROSS_BORDER_CORRIDOR',
    lat: 23.8103,
    lng: 90.4125,
    fugitiveCount: 7,
    topOffenses: ['Eastern Border Infiltration', 'Cross-Border Gold & Cattle Smuggling', 'FICN Distribution'],
    extraditionStatus: 'Revised Extradition Treaty Signed 2016; Active BSF-BGB Security Dialogue',
    interpolArticle: 'Interpol Red Notice Border Alert',
    investigativeRationale: 'Smuggling route feeding counterfeit currency into West Bengal and Assam financial channels.',
    linkedFugitiveIds: ['P-047', 'P-192'],
    keyPersons: ['Ramesh Yadav (P-047)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-SGP',
    name: 'Singapore Maritime Hub',
    country: 'Singapore',
    countryCode: 'SG',
    flag: '🇸🇬',
    category: 'TRANSIT_HUB',
    lat: 1.3521,
    lng: 103.8198,
    fugitiveCount: 8,
    topOffenses: ['Trade-Based Money Laundering', 'Container Cargo Fraud', 'Shell Offshore SPVs'],
    extraditionStatus: 'Extradition Arrangement via Commonwealth Framework / MLAT Active',
    interpolArticle: 'Interpol Red Notice Art. 83 Financial Taskforce',
    investigativeRationale: 'International shipping corridor used to over-invoice commodities and park illegal proceeds in Asian private wealth accounts.',
    linkedFugitiveIds: ['P-010', 'P-031'],
    keyPersons: ['Ajay Sharma (P-010)', 'Pankaj Saxena (P-031)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-THA',
    name: 'Bangkok & Pattaya Corridor',
    country: 'Thailand',
    countryCode: 'TH',
    flag: '🇹🇭',
    category: 'TRANSIT_HUB',
    lat: 13.7563,
    lng: 100.5018,
    fugitiveCount: 5,
    topOffenses: ['Narcotics Transit (Golden Triangle)', 'Casino Money Laundering', 'Synthetic Drugs'],
    extraditionStatus: 'Extradition Treaty Signed 2013; Active Royal Thai Police Liaison',
    interpolArticle: 'Interpol Red Notice Narcotics Interdiction',
    investigativeRationale: 'Re-routing depot for precursor chemicals and Southeast Asian synthetic drug distribution networks.',
    linkedFugitiveIds: ['P-007', 'P-040'],
    keyPersons: ['Prasad Rao (P-007)', 'Tushar Kamble (P-040)'],
    treatyStatus: 'IN_FORCE',
  },

  // ── DOMESTIC INDIAN OPERATIONAL HUBS ─────────────────────────
  {
    id: 'HOTSPOT-MUMBAI',
    name: 'Mumbai Metropolitan Region',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'DOMESTIC_SYNDICATE',
    lat: 19.0760,
    lng: 72.8777,
    fugitiveCount: 15,
    topOffenses: ['Narcotics Distribution', 'Extortion Syndicates', 'Organized Gang Warfare (MCOCA)', 'Hawala Clearing'],
    extraditionStatus: 'Primary Prosecution Jurisdiction (Sessions Court & MCOCA Special Court, Mumbai)',
    interpolArticle: 'Originating CBI / Crime Branch Special Investigation Division',
    investigativeRationale: 'Operational hub of Shadow Syndicate (Cluster A). Connected to live street CCTV telemetry, traffic choke points, and port transit nodes.',
    linkedFugitiveIds: ['P-001', 'P-002', 'P-003', 'P-004', 'P-005', 'P-006', 'P-007', 'P-008', 'P-009', 'P-010', 'P-011', 'P-012', 'P-013', 'P-014', 'P-015', 'P-017'],
    keyPersons: ['Arjun Patel (P-003)', 'Vikram Reddy (P-017)', 'Prasad Rao (P-007)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-PUNJAB',
    name: 'Punjab Border Belt',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'DOMESTIC_SYNDICATE',
    lat: 30.9010,
    lng: 75.8573,
    fugitiveCount: 34,
    topOffenses: ['Cross-Border Drone Arms Smuggling', 'Heroin Trafficking (NDPS Act)', 'Targeted Extortion', 'Inter-Gang Clashes'],
    extraditionStatus: 'Punjab Police Special Operations Group / NIA Active Warrants',
    interpolArticle: 'Interpol Red Notice Border Alert (Amritsar, Tarn Taran, Jalandhar)',
    investigativeRationale: 'High-density border region facing persistent cross-border weapon drops and syndicated extortion networks coordinated from Canadian and European sanctuaries.',
    linkedFugitiveIds: ['P-035', 'P-036', 'P-037', 'P-038', 'P-039', 'P-040', 'P-041', 'P-042', 'P-043', 'P-044'],
    keyPersons: ['Deepak Joshi (P-038)', 'Prashant Jagtap (P-042)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-MANIPUR',
    name: 'Manipur & Northeast Frontier',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'DOMESTIC_SYNDICATE',
    lat: 24.8170,
    lng: 93.9368,
    fugitiveCount: 32,
    topOffenses: ['Armed Insurgent Warfare (UAPA Sec 16)', 'Arms Looting & Trafficking', 'Extortion from State Contracts'],
    extraditionStatus: 'Special NIA Court Imphal / Home Ministry Proscribed Organizations Registry',
    interpolArticle: 'Interpol Red Notice Sovereign Threat Alert (Art. 83)',
    investigativeRationale: 'Cross-border sanctuaries across Myanmar frontier utilized for staging insurgent logistics and tactical weaponry acquisition.',
    linkedFugitiveIds: ['P-001'],
    keyPersons: ['Maipak Khuraijam (P-001)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-DELHI',
    name: 'Delhi NCR Capital Hub',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'DOMESTIC_SYNDICATE',
    lat: 28.6139,
    lng: 77.2090,
    fugitiveCount: 9,
    topOffenses: ['Financial Fraud (IPC 420)', 'Shell Corporate Laundering', 'Bank Embezzlement', 'Hawala Distribution'],
    extraditionStatus: 'Patiala House Courts / CBI Special Courts New Delhi',
    interpolArticle: 'Interpol Red Notice Economic Crimes Enforcement',
    investigativeRationale: 'Command hub of Golden Circuit (Cluster B). Coordinates large-scale banking fraud, benami corporate directors, and political lobbying.',
    linkedFugitiveIds: ['P-020', 'P-021', 'P-022', 'P-023', 'P-024', 'P-025', 'P-026', 'P-027', 'P-028'],
    keyPersons: ['Suresh Gupta (P-022)', 'Yogesh Bhatia (P-025)', 'Tarun Sethi (P-028)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-GUJARAT',
    name: 'Gujarat Coastal & Mercantile Belt',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'DOMESTIC_SYNDICATE',
    lat: 23.0225,
    lng: 72.5714,
    fugitiveCount: 17,
    topOffenses: ['Maritime Contraband Infiltration', 'Customs Duty Evasion', 'Hawala Gold Transits'],
    extraditionStatus: 'Gujarat Police ATS & Directorate of Revenue Intelligence (DRI) Warrants',
    interpolArticle: 'Interpol Red Notice Maritime Watch',
    investigativeRationale: 'Vast coastline and major ports (Mundra, Kandla) exploited by transnational syndicates for high-volume contraband landing.',
    linkedFugitiveIds: ['P-008', 'P-011', 'P-032'],
    keyPersons: ['Amit Verma (P-032)', 'Kiran Naik (P-008)'],
    treatyStatus: 'IN_FORCE',
  },
  {
    id: 'HOTSPOT-JAMMU',
    name: 'Jammu & Kashmir Border Sector',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    category: 'CROSS_BORDER_CORRIDOR',
    lat: 32.7266,
    lng: 74.8570,
    fugitiveCount: 10,
    topOffenses: ['LoC Cross-Border Infiltration', 'Terrorist Financing', 'Narcotics-Terror Nexus (UAPA)'],
    extraditionStatus: 'Jammu & Kashmir Police Special Operations / NIA Terror Funding Registry',
    interpolArticle: 'Interpol Red Notice Border Security Enforcement',
    investigativeRationale: 'High-risk frontier sector subject to kinetic cross-border weapon caches and subversive financial transfers.',
    linkedFugitiveIds: ['P-017', 'P-045'],
    keyPersons: ['Vikram Reddy (P-017)', 'Irfan Sheikh (P-045)'],
    treatyStatus: 'IN_FORCE',
  },
];

export const TRANSNATIONAL_FLIGHT_ARCS: FlightArc[] = [
  {
    id: 'ARC-UAE-MUM',
    sourceId: 'HOTSPOT-UAE',
    sourceName: 'Dubai (UAE)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [55.2708, 25.2048],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'FINANCIAL_LAUNDERING',
    description: 'Hawala financial clearing and proxy corporate direction connecting Gulf shell accounts to Mumbai crime operatives.',
    density: 'CRITICAL',
  },
  {
    id: 'ARC-UK-MUM',
    sourceId: 'HOTSPOT-UK',
    sourceName: 'London (UK)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [-0.1278, 51.5074],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'EXTRADITION_TRANSIT',
    description: 'Transnational capital flight and legal defense funding for fugitives fighting court extradition proceedings.',
    density: 'HIGH',
  },
  {
    id: 'ARC-CAN-PUN',
    sourceId: 'HOTSPOT-CAN',
    sourceName: 'Toronto (Canada)',
    targetId: 'HOTSPOT-PUNJAB',
    targetName: 'Punjab (India)',
    sourceCoords: [-79.3832, 43.6532],
    targetCoords: [75.8573, 30.9010],
    corridorType: 'LOGISTICS_SMUGGLING',
    description: 'Encrypted communication channel funding contract violence, extortion calls, and arms procurement across northern districts.',
    density: 'CRITICAL',
  },
  {
    id: 'ARC-PAK-MUM',
    sourceId: 'HOTSPOT-PAK',
    sourceName: 'Karachi (Pakistan)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [69.3451, 30.3753],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'INSURGENCY_TRANSIT',
    description: 'Maritime landing route for contraband, counterfeit Indian currency (FICN), and syndicate weapon caches.',
    density: 'HIGH',
  },
  {
    id: 'ARC-NEP-DEL',
    sourceId: 'HOTSPOT-NEP',
    sourceName: 'Kathmandu (Nepal)',
    targetId: 'HOTSPOT-DELHI',
    targetName: 'Delhi (India)',
    sourceCoords: [84.1240, 28.3949],
    targetCoords: [77.2090, 28.6139],
    corridorType: 'EXTRADITION_TRANSIT',
    description: 'Porous overland transit corridor used by absconding white-collar and narcotics conspirators to evade immigration biometric watchlists.',
    density: 'HIGH',
  },
  {
    id: 'ARC-ROU-MUM',
    sourceId: 'HOTSPOT-ROU',
    sourceName: 'Bucharest (Romania)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [24.9668, 45.9432],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'FINANCIAL_LAUNDERING',
    description: 'Cyber skimming and cryptocurrency laundering exchange channel forwarding stolen credentials to domestic bank accounts.',
    density: 'MEDIUM',
  },
  {
    id: 'ARC-SGP-MUM',
    sourceId: 'HOTSPOT-SGP',
    sourceName: 'Singapore',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [103.8198, 1.3521],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'FINANCIAL_LAUNDERING',
    description: 'Trade-based over-invoicing route parking syndicate proceeds in Southeast Asian offshore accounts before domestic re-investment.',
    density: 'HIGH',
  },
  {
    id: 'ARC-USA-DEL',
    sourceId: 'HOTSPOT-USA',
    sourceName: 'New York (USA)',
    targetId: 'HOTSPOT-DELHI',
    targetName: 'Delhi (India)',
    sourceCoords: [-74.0060, 40.7128],
    targetCoords: [77.2090, 28.6139],
    corridorType: 'FINANCIAL_LAUNDERING',
    description: 'Transatlantic wire transfer fraud channel routing compromised corporate payouts through shell banking conduits in Delhi NCR.',
    density: 'HIGH',
  },
  {
    id: 'ARC-BGD-KOL',
    sourceId: 'HOTSPOT-BGD',
    sourceName: 'Dhaka (Bangladesh)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Kolkata / Eastern Corridor',
    sourceCoords: [90.4125, 23.8103],
    targetCoords: [88.3639, 22.5726],
    corridorType: 'LOGISTICS_SMUGGLING',
    description: 'Porous riverine border crossing funneling high-grade fake currency notes into Eastern Indian commercial circulation.',
    density: 'MEDIUM',
  },
  {
    id: 'ARC-THA-MUM',
    sourceId: 'HOTSPOT-THA',
    sourceName: 'Bangkok (Thailand)',
    targetId: 'HOTSPOT-MUMBAI',
    targetName: 'Mumbai (India)',
    sourceCoords: [100.5018, 13.7563],
    targetCoords: [72.8777, 19.0760],
    corridorType: 'LOGISTICS_SMUGGLING',
    description: 'Air cargo courier route smuggling synthetic methamphetamine precursors disguised as pharmaceutical consignments.',
    density: 'MEDIUM',
  },
];

export const MAP_TAXONOMY_EXPLANATION = [
  {
    sign: '🔴 Glowing Red Dot / Hotspot Badge',
    target: 'Interpol Red Notice Sanctuary / Hotspot',
    whyRenders: 'Renders extraterritorial jurisdictions where subjects wanted under Interpol Article 83 notices reside or maintain bank accounts.',
    reason: 'Enables bilateral extradition tracking (MEA), INTERPOL NCB coordination, and asset restraint under PMLA Section 5.',
    color: '#FF1744',
  },
  {
    sign: '🟢 Emerald Pin Glyph',
    target: 'Jurisdictional Police Hub / Primary Crime Scene',
    whyRenders: 'Renders verified domestic police precincts, FIR crime scenes, and forensic seizure sites.',
    reason: 'Establishes local territorial jurisdiction, charge sheet filings, and physical evidence chain of custody admissible under BSA 2023.',
    color: '#10B981',
  },
  {
    sign: '🟡 Amber Camera Lens Glyph',
    target: 'Urban Optical CCTV Sensor (Live Stream / PTZ)',
    whyRenders: 'Renders municipal surveillance cameras with real RTSP/HLS live feeds and street coverage buffers.',
    reason: 'Empowers command room operators to optically verify suspect movements at critical choke points and perform immediate vehicle interdiction.',
    color: '#FFB300',
  },
  {
    sign: '🚦 Traffic Signal Phase Glyph',
    target: 'Smart Traffic Controller (SCATS / ITMS)',
    whyRenders: 'Renders live intersection traffic signal phases (Red, Yellow, Green) and queue congestion metrics.',
    reason: 'Enables green-corridor tactical containment to intercept getaway vehicles before they escape municipal exit highways.',
    color: '#00D4FF',
  },
  {
    sign: '🟣 Purple Diamond Glyph',
    target: 'Timeline Sighting / Sensor Incident',
    whyRenders: 'Renders timestamped wiretap captures, ANPR vehicle sightings, and CDR geo-located call events.',
    reason: 'Provides chronological corroboration of suspect presence to prove criminal co-conspiracy and refute fabricated alibis in court.',
    color: '#A855F7',
  },
  {
    sign: '🔷 Curved Transnational Arc',
    target: 'Cross-Border Logistics / Hawala Corridor',
    whyRenders: 'Renders high-probability smuggling, money laundering, and flight transit arcs connecting overseas sanctuaries to India.',
    reason: 'Identifies transnational transit chokepoints and triggers Financial Intelligence Unit (FIU-IND) / Customs interdictions.',
    color: '#4FC3F7',
  },
];
